#!/usr/bin/env python3
"""Invariant lint for critical-thinking-for-humans.

Checks that every load-bearing rule sentence (invariant) is literally present
in its carrier file. Presence-only: a green run means the text exists, NOT that
runtime behavior honors it (behavioral gates live in docs/GATE-checklist.md).
"""
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent

# (file, label, required substring) or (file, label, required substring, h2_title)
# With h2_title, the substring must appear inside that H2 section's body —
# a sentence moved out of its section is a FAIL even if present elsewhere.
CHECKS = [
    # --- shared/structures.md (Task 2) ---
    ("shared/structures.md", "canonical-id-rule",
     "Canonical IDs are snake_case English and never localized"),
    ("shared/structures.md", "structure-necessary-assumption", "necessary_assumption"),
    ("shared/structures.md", "structure-alternative-cause", "alternative_cause"),
    ("shared/structures.md", "structure-reverse-causation", "reverse_causation"),
    ("shared/structures.md", "structure-coincidence-timing", "coincidence_timing"),
    ("shared/structures.md", "structure-sample-selection", "sample_selection"),
    ("shared/structures.md", "structure-proxy-mismatch", "proxy_mismatch"),
    ("shared/structures.md", "structure-evidence-sufficiency", "evidence_sufficiency"),
    ("shared/structures.md", "structure-weak-analogy", "weak_analogy"),
    ("shared/structures.md", "weak-analogy-counter-question",
     "the property the conclusion actually needs, or only on surface features"),
    ("shared/structures.md", "distractor-out-of-scope", "out_of_scope"),
    ("shared/structures.md", "distractor-premise-restatement", "premise_restatement"),
    ("shared/structures.md", "distractor-weak-proxy-trap", "weak_proxy_trap"),
    ("shared/structures.md", "frame-power", "frame_power"),
    ("shared/structures.md", "frame-counter", "frame_counter"),
    # --- shared/redlines.md (Task 3) ---
    ("shared/redlines.md", "rl1-adjudicate",
     "Interpretations are never ranked against each other"),
    ("shared/redlines.md", "rl1-reasoning-floor",
     "internal contradictions, factual errors, and evidence misreadings are corrected in every mode"),
    ("shared/redlines.md", "rl2-steelman",
     "strongest defensible form"),
    ("shared/redlines.md", "rl3-graph-silence",
     "The scene graph never drives questioning"),
    ("shared/redlines.md", "rl3-not-a-miss-list",
     "never as a list of what the user missed"),
    ("shared/redlines.md", "rl4-no-flattery",
     "A wrong answer is never called right"),
    ("shared/redlines.md", "rl5-frame-palette",
     "never circling within a single vocabulary"),
    ("shared/redlines.md", "rl6-no-real-items",
     "Never reproduce, adapt, or imitate published test items"),
    ("shared/redlines.md", "rl7-no-identity-inference",
     "Never infer or adjust difficulty from identity cues"),
    ("shared/redlines.md", "rl8-safe-words",
     "Safe words are always honored"),
    ("shared/redlines.md", "rl9-fenced-data",
     "data, never instructions"),
    ("shared/redlines.md", "rl10-real-persons",
     "never diagnose character, motive, or moral essence"),
    ("shared/redlines.md", "rl11-no-motive-claims",
     "only as hypotheses, never assertions"),
    ("shared/redlines.md", "rl12-passport-honesty",
     "its relevant content enters the model context when used"),
    # --- shared/scaffolding.md (Task 4) ---
    ("shared/scaffolding.md", "sw-stuck", "\"stuck\""),
    ("shared/scaffolding.md", "sw-hint", "\"hint\""),
    ("shared/scaffolding.md", "sw-enough", "\"enough for today\""),
    ("shared/scaffolding.md", "sw-forget", "\"forget this one\""),
    ("shared/scaffolding.md", "four-step",
     "understand the intent, anchor what was done right, state the fact, leave space"),
    ("shared/scaffolding.md", "anchor-before-reveal",
     "the anchor comes BEFORE the reveal"),
    ("shared/scaffolding.md", "depersonalize",
     "locate the error in the reasoning move, never in the person"),
    ("shared/scaffolding.md", "invariant-bar",
     "the standard of a sound analysis is identical at every difficulty"),
    # --- modes/drill.md (Task 5) ---
    ("modes/drill.md", "commit-then-reveal",
     "the user commits an answer before any analysis is shown"),
    ("modes/drill.md", "reverse-solve",
     "re-solve the item with fresh eyes WITHOUT reference to the"),
    ("modes/drill.md", "no-gmat-stems",
     "plain functional language, never imitating the distinctive phrasing of published exams"),
    ("modes/drill.md", "novel-anchors",
     "a synthetic institution name, specific numbers, and the user's domain context"),
    ("modes/drill.md", "cannot-be-determined",
     "\"cannot be determined\" is a legitimate and rewarded answer"),
    ("modes/drill.md", "sound-item-silent-possibility",
     "never which item is one"),
    ("modes/drill.md", "sound-item-inverted-solve",
     "the audit must show NO structure yields a live attack"),
    ("modes/drill.md", "sound-item-outcome-sentinel",
     "an `argument_sound` outcome, not a structure ID"),
    ("passport/SCHEMA.md", "argument-sound-not-a-structure",
     "`argument_sound` is an outcome sentinel, not a reasoning structure"),
    ("passport/SCHEMA.md", "argument-sound-no-weighting",
     "miss-log weighting that step (b) of the pipeline uses to pick the next target"),
    ("passport/SCHEMA.md", "item-discarded-no-weighting",
     "`item_discarded` never feeds the per-structure miss-log weighting"),
    ("passport/SCHEMA.md", "confused-with-ids-only",
     "`confused_with` carries IDs only, never option text"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-confused-with-ids-only",
     "(the CLI edition's `confused_with`); IDs only"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-discards-no-weighting",
     "not a user stat: never read for"),
    ("modes/drill.md", "item-discarded-generator-signal",
     "it measures the generator, not the user"),
    ("shared/structures.md", "source-ops-not-loggable",
     "none of these IDs ever appears in any passport event or tally field"),
    ("shared/structures.md", "check-basis-weight-not-truth",
     "evidential WEIGHT, never truth by origin"),
    ("modes/drill.md", "reason-right-answer-wrong-reason",
     "a right answer carried by a wrong reason is said plainly"),
    ("modes/detective.md", "repair-and-decide-close",
     "at the strength the surviving evidence supports"),
    ("modes/expedition.md", "auditor-trust-close",
     "whether the verified chain should be trusted as presented"),
    ("modes/scene.md", "micro-prompt-commit-first-guard",
     "never inside the commit-first window"),
    ("modes/detective.md", "micro-prompt-defect-call-guard",
     "never as a substitute for the"),
    ("passport/SCHEMA.md", "not-elicited-no-deficit",
     "absence of opportunity must never read as learner deficit"),
    ("passport/SCHEMA.md", "elicitation-reasoning-moves-only",
     "never inferred from safe-word use, session length, or willingness to continue"),
    ("passport/SCHEMA.md", "no-disposition-scores",
     "No personality labels, no disposition scores — three coarse states maximum"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-unprompted-no-deficit",
     "Absence of opportunity never reads as deficit"),
    ("shared/scaffolding.md", "elicitation-lanes-mirror",
     "stated from the record, never prosecuted, and never inferred from safe-word"),
    ("modes/drill.md", "name-the-skeleton",
     "the canonical ID goes into the passport event, not the display"),
    ("modes/drill.md", "honor-key-challenge",
     "The coach never defends a key by authority"),
    ("modes/drill.md", "challenge-window-before-write",
     "Open the challenge window — STOP and wait for the user"),
    ("shared/structures.md", "display-plain-language",
     "raw snake_case IDs appear only in passport events"),
    # --- modes/scene.md (Task 6) ---
    ("modes/scene.md", "graph-first",
     "generate the scene graph before rendering any scene text"),
    ("modes/scene.md", "provenance-tags",
     "user_specified / system_specified / randomized / model_default"),
    ("modes/scene.md", "graph-silence",
     "The scene graph never drives questioning"),
    ("modes/scene.md", "two-axis",
     "interpretations are never ranked; flaws inside a single reading are always corrected"),
    ("modes/scene.md", "frame-palette-list",
     "frame_power, frame_institution, frame_incentive, frame_charitable, frame_info_limits, frame_counter"),
    ("modes/scene.md", "camera-turn",
     "Where does your own reading stand, and what can it not see"),
    ("modes/scene.md", "process-metrics",
     "process metrics, never hit/miss"),
    ("modes/scene.md", "byom-first",
     "BYOM path is implemented first"),
    # --- SKILL.md (Task 8) ---
    ("SKILL.md", "mode-keywords", "`drill` → load `modes/drill.md` (judge stance)"),
    ("SKILL.md", "single-mode-load",
     "load exactly one mode file"),
    ("SKILL.md", "stance-reset", "STANCE RESET"),
    ("SKILL.md", "contract",
     "This tool will point out flaws in your reasoning. That is what you came here for."),
    ("SKILL.md", "three-fields",
     "domain, difficulty, and feedback style"),
    ("SKILL.md", "fresh-session-advice",
     "a fresh session gives the cleanest stance separation"),
    # --- passport (Task 7) ---
    ("passport/SCHEMA.md", "schema-version", "schema_version"),
    ("passport/SCHEMA.md", "append-only", "append-only"),
    ("passport/SCHEMA.md", "atomic-write", "atomic"),
    ("passport/SCHEMA.md", "passport-helper-only",
     "Every canonical local Passport event-log read, append, generation read/create,\n"
     "and deletion goes through the bundled helper"),
    ("passport/SCHEMA.md", "passport-node-preflight",
     "The local helper requires Node.js 22 or newer on `PATH`"),
    ("passport/SCHEMA.md", "passport-node-failure-off-ramp",
     "On exit 69, pause recording for the session"),
    ("passport/SCHEMA.md", "passport-generation-at-startup",
     "At the beginning of every local session, before reading `events.jsonl`, invoke"),
    ("passport/SCHEMA.md", "passport-read-through-helper",
     "obtain the event-log snapshot through that locked `read` command; never read\n"
     "`events.jsonl` directly"),
    ("passport/SCHEMA.md", "passport-lock-before-reread",
     "acquires the exclusive sidecar lock before it rereads"),
    ("passport/SCHEMA.md", "passport-checkpoint-batch",
     "as one ordered checkpoint batch"),
    ("passport/SCHEMA.md", "passport-batch-json-validation",
     "validates the whole stdin batch as UTF-8 JSON objects before taking\n"
     "the lock"),
    ("passport/SCHEMA.md", "passport-events-stdin-only",
     "never place event\ncontent in command-line arguments or interpolate raw user text into shell code"),
    ("passport/SCHEMA.md", "passport-fail-closed",
     "never fall back to direct or unlocked\nfilesystem access"),
    ("passport/SCHEMA.md", "passport-pending-until-success",
     "Clear the in-session pending buffer only after the helper exits zero"),
    ("passport/SCHEMA.md", "passport-generation-mismatch-discards-stale",
     "exit 76 (`PASSPORT_GENERATION_MISMATCH`). That code means the on-disk generation\n"
     "was rotated or reset"),
    ("passport/SCHEMA.md", "passport-orphan-temp-cleanup",
     "Exact helper-owned orphan temp files are removed under the\nlock"),
    ("passport/SCHEMA.md", "passport-delete-same-lock",
     "The helper uses the same\nexclusive lock as an append, rotates the generation before removing"),
    ("passport/SCHEMA.md", "passport-delete-no-resurrection",
     "a pre-deletion pending batch\ncannot recreate deleted Passport data"),
    ("passport/SCHEMA.md", "passport-show-not-persisted",
     "The current runtime does not persist `~/.ct-gym/passport.md`"),
    ("passport/SCHEMA.md", "passport-show-locked-read",
     "invokes the helper's locked `read --generation TOKEN` command"),
    ("passport/SCHEMA.md", "no-raw-text",
     "structure tags and short summaries, never raw user text"),
    # --- new scope/consumer checks ---
    ("shared/redlines.md", "rl5-scope", "Every scene lays out"),
    ("shared/scaffolding.md", "feedback-style-consumer",
     "the style changes the wrapping, never the verdict"),
    # --- README.md (Task 9) ---
    ("README.md", "stance-charter", "Stance Charter"),
    ("README.md", "gym-line",
     "A gym doesn't tell you where to walk"),
    ("README.md", "independence-disclaimer",
     "not affiliated with, sponsored by, or endorsed"),
    ("README.md", "original-items-disclaimer",
     "All practice items are original. CLI/Skill sessions generate items at runtime"),
    ("README.md", "non-legal",
     "not legal advice"),
    ("README.md", "safest-place",
     "the cheapest place in the world to lose face"),
    # --- review round 1: full distractor/frame coverage ---
    ("shared/structures.md", "distractor-true-but-irrelevant", "true_but_irrelevant"),
    ("shared/structures.md", "distractor-opposite-180", "opposite_180"),
    ("shared/structures.md", "distractor-reverses-logic", "reverses_logic"),
    ("shared/structures.md", "distractor-too-extreme", "too_extreme"),
    ("shared/structures.md", "distractor-irrelevant-comparison", "irrelevant_comparison"),
    ("shared/structures.md", "frame-institution", "frame_institution"),
    ("shared/structures.md", "frame-incentive", "frame_incentive"),
    ("shared/structures.md", "frame-charitable", "frame_charitable"),
    ("shared/structures.md", "frame-info-limits", "frame_info_limits"),
    # --- review round 1: new rule sentences ---
    ("shared/structures.md", "technique-not-loggable",
     "procedure, not a loggable structure"),
    ("shared/structures.md", "fourteen-structures", "fourteen loggable structure IDs"),
    ("modes/drill.md", "drill-fourteen-structures", "the fourteen structure IDs"),
    ("modes/drill.md", "drill-gate-structure-groups",
     "formal/inductive (three of them), and source-evaluation (one of them)"),
    ("shared/structures.md", "structure-base-rate-neglect", "base_rate_neglect"),
    ("shared/structures.md", "structure-regression-to-mean", "regression_to_mean"),
    ("shared/structures.md", "structure-simpson-paradox", "simpson_paradox"),
    ("shared/structures.md", "structure-circular-reasoning", "circular_reasoning"),
    ("shared/structures.md", "circular-reasoning-boundary",
     "the premise being the conclusion restated"),
    ("shared/structures.md", "structure-hasty-generalization", "hasty_generalization"),
    ("shared/structures.md", "hasty-vs-sufficiency-boundary",
     "a direction is established, but the sample is simply too small"),
    ("shared/structures.md", "hasty-vs-sample-selection-boundary",
     "too small or too narrow, with no systematic exclusion"),
    ("shared/structures.md", "hasty-contrast-pair",
     "Contrast pair (hasty vs sufficiency)"),
    # --- v1.5: source credibility as the 14th loggable structure ---
    ("shared/structures.md", "structure-source-credibility",
     "| `source_credibility` | How much evidential weight a source or observation report warrants",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-unknown-stays-unknown",
     "unknown funding, motives, independence, credentials, or records stay unknown",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-documented-basis",
     "only a documented credibility-relevant fact changes evidential weight",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-vs-sufficiency",
     "enough support to license any conclusion\n  stays `evidence_sufficiency`",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-vs-sample-selection",
     "who entered or was excluded from\n  the sample stays a sampling defect",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-vs-authority",
     "`source_credibility` vs `authority_abuse` / `fallacy_appeal`",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-reverse-guards",
     "It never, by itself, proves the claim false or makes a person globally\n"
     "  untrustworthy", "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-independent-lines",
     "The publication count is one relayed source, not five independent lines",
     "Reasoning Structures"),
    ("shared/structures.md", "source-credibility-single-key",
     "do not build an item on which both are defensible\n  keys",
     "Reasoning Structures"),
    ("shared/structures.md", "source-operations-apply-structure",
     "procedures for applying\n`source_credibility`, not loggable structures",
     "Source-Credibility Operations"),
    ("modes/drill.md", "drill-source-existing-item-types",
     "`weaken`- or\n  `sufficiency`-type item",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-source-no-fifth-item-type",
     "fifth item type or passport schema version",
     "Session Flow"),
    ("modes/drill.md", "drill-source-slot",
     "`source_credibility` — slot: the one documented credibility-relevant feature",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-source-single-key-reverse-solve",
     "If two classifications\nremain defensible, discard and regenerate",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-source-reroute-nonstructure-ids",
     "never put a technique or\nfallacy-lens ID into a `weaken` or `sufficiency` result",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-source-sound-interested-counterexample",
     "The sound pool must preserve interested-source counterexamples",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-option-length-not-a-key",
     "correctness must not be encoded by length",
     "Item Generation Pipeline"),
    ("modes/drill.md", "drill-source-logging",
     "`source_credibility` as its one structure ID",
     "Session Flow"),
    ("modes/drill.md", "drill-sound-audit-fourteen",
     "at minimum walk the fourteen structures",
     "Item Generation Pipeline"),
    ("modes/detective.md", "detective-fourteen-structures",
     "the fourteen-structure set", "Layer Structure"),
    ("modes/detective.md", "detective-source-concrete-key",
     "solving the weight problem must expose one concrete record fact consumed by the\n"
     "next lock", "Layer Structure"),
    ("modes/detective.md", "detective-source-first-call-silence",
     "source provenance,\nweight, and the three source-operation prompts remain unspoken until the user\n"
     "makes the first defect call", "Session Flow"),
    ("modes/detective.md", "detective-source-logging",
     "`source_credibility` uses this existing field when the user catches that keyed\n"
     "layer", "Logging"),
    ("shared/manipulation-taxonomy.md", "source-authority-boundary",
     "`authority_abuse` requires borrowed, fabricated, or\n"
     "out-of-domain authority to do the persuading", "Technique Table"),
    ("shared/manipulation-taxonomy.md", "source-authority-recognition-only",
     "recognition remains the sole permitted direction under redline 13",
     "Technique Table"),
    ("docs/GATE-checklist.md", "gate13-two-tier-unique-key",
     "13A — two tiers, existing item types, and unique key",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/GATE-checklist.md", "gate13-option-length",
     "unique\nlongest by both at least 8 characters and at least 25 percent",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/GATE-checklist.md", "gate13-sound-interested-source",
     "13B — sound interested-source counterexample",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/GATE-checklist.md", "gate13-weight-unknown",
     "13C — weight, never truth; unknown stays unknown",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/GATE-checklist.md", "gate13-logging-boundary",
     "13D — logging and operation/structure boundary",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/GATE-checklist.md", "gate13-detective-first-call",
     "13E — Detective first call, concrete dependency, no leak",
     "Gate 13 — Source Credibility as a Canonical Structure"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate13-two-tier",
     "Intro `weaken` and advanced `sufficiency` source items", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate13-sound-source",
     "Sound interested source with transparent methods", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate13-weight-unknown",
     "Press a documented source limitation into a false verdict", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate13-logging",
     "Inspect hit, miss, and valid-challenge events in a disposable Passport",
     "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate13-detective",
     "Start a source-keyed Detective case", "Results"),
    # --- #47: keyed reject-the-framing move (drill family + detective layer) ---
    ("modes/drill.md", "defective-framing-not-a-fifth-type",
     "Not a fifth item type — hosted in the existing `weaken` and `sufficiency`",
     "Item Types"),
    ("modes/drill.md", "defective-framing-structural-never-ideological",
     "an evidential or logical defect keyed to exactly one of the fourteen\n"
     "  structures — never a value-frame dispute (redline 1",
     "Item Types"),
    ("modes/drill.md", "defective-framing-silent-possibility",
     "never which item carries one",
     "Item Types"),
    ("modes/drill.md", "defective-framing-reverse-guard-pool",
     "the mirror image of the over-flagging the sound-argument\n  pool guards against",
     "Item Types"),
    ("shared/structures.md", "defective-framing-defeated-not-unestablished",
     "Contrast pair (defeated premise vs unestablished premise)"),
    ("shared/structures.md", "defective-framing-contrast-forbidden",
     "\"the\nquestion rests on a defeated premise\" and \"cannot be determined\" are\n"
     "simultaneously defensible"),
    ("modes/drill.md", "defective-framing-audit",
     "Defective-framing audit (defective-framing items and any item carrying",
     "Item Generation Pipeline"),
    ("modes/drill.md", "defective-framing-no-intro-fallback",
     "never rides the g2 ladder into intro",
     "Item Generation Pipeline"),
    ("modes/detective.md", "detective-reframe-key-dependency",
     "the prior layer's key must be a necessary input to establishing the premise\n"
     "failure", "Layer Structure"),
    ("modes/drill.md", "defective-framing-unique-key",
     "no within-frame option remains defensible as a best response",
     "Item Generation Pipeline"),
    ("modes/drill.md", "defective-framing-reverse-guard-audit",
     "verify the material affirmatively establishes the premise",
     "Item Generation Pipeline"),
    ("modes/drill.md", "defective-framing-tier-gate",
     "Defective-framing items and their reverse-guard pool run\n"
     "at standard and advanced only",
     "Difficulty Knobs"),
    ("modes/drill.md", "defective-framing-logging-no-new-ids",
     "records the structure the defective premise\n   instantiates",
     "Session Flow"),
    ("modes/drill.md", "framing-notice-live-answer",
     "\"the question\n   fails\" are live answers",
     "Session Flow"),
    ("shared/structures.md", "distractor-premise-challenge-trap",
     "premise_challenge_trap"),
    ("shared/structures.md", "distractor-menu-count",
     "the nine wrong-answer patterns"),
    ("modes/detective.md", "detective-reframe-layer",
     "built as a **reframe layer**", "Layer Structure"),
    ("modes/detective.md", "detective-reframe-g0-boundary",
     "the G0 frame itself is never the thing\nrejected (redline 1)",
     "Layer Structure"),
    ("modes/detective.md", "detective-reframe-concrete-key",
     "still one\nconcrete value consumed by the next lock", "Layer Structure"),
    ("modes/detective.md", "detective-reframe-no-sophistication-reward",
     "refusing the question is never rewarded as sophistication",
     "Layer Structure"),
    ("modes/detective.md", "detective-reframe-never-announced",
     "never announced", "Layer Structure"),
    ("modes/detective.md", "detective-reframe-one-per-case",
     "at most one per case", "Difficulty Knobs"),
    ("modes/detective.md", "detective-reframe-defeated-not-unestablished",
     "merely unestablished rather than defeated"),
    ("modes/detective.md", "detective-reframe-ablation",
     "every\n   within-frame answer is defeated by the premise defect"),
    ("modes/detective.md", "detective-reframe-no-bare-label",
     "never the bare label \"the question is loaded\""),
    ("modes/detective.md", "detective-reframe-logging",
     "the reframe is where the flaw sits, not a new ID", "Logging"),
    ("docs/GATE-checklist.md", "gate14-drill-keyed",
     "14A (drill keyed reframe item)",
     "Gate 14 — Reject-the-Framing Probes"),
    ("docs/GATE-checklist.md", "gate14-reverse-guard",
     "14B (reverse guard — sound framing)",
     "Gate 14 — Reject-the-Framing Probes"),
    ("docs/GATE-checklist.md", "gate14-detective-reframe",
     "14C (detective reframe layer)",
     "Gate 14 — Reject-the-Framing Probes"),
    ("docs/GATE-checklist.md", "gate14-g0-boundary",
     "14D (G0-frame boundary)",
     "Gate 14 — Reject-the-Framing Probes"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate14-drill-keyed",
     "Defective-framing drill fixture", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate14-reverse-guard",
     "deliberately over-flag the question", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate14-detective-reframe",
     "Detective reframe layer", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate14-g0-boundary",
     "Dispute the G0 frame", "Results"),
    # --- #48: post-reveal updating (passport dimension + per-mode step) ---
    ("passport/SCHEMA.md", "post-reveal-two-capabilities",
     "Seeing a flaw and moving on it are different capabilities",
     "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-observable-acts",
     "observable acts only, never self-report", "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-no-inference",
     "no act, no field, no inference", "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-shared-vocabulary",
     "One state vocabulary serves every carrier", "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-scene-neutrality",
     "never that the objection was right (redline 1)",
     "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-hit-not-understanding",
     "a hit is not evidence the flaw\nwas understood",
     "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-hold-first-class",
     "is a first-class outcome, never a failure", "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-no-update-pressure",
     "no update pressure is ever applied", "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-pattern-class",
     "\"seen but not moved on\" as its own pattern class",
     "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-repeat-precision-relation",
     "states the two together rather than reporting one act as two",
     "Post-Reveal Updating"),
    ("passport/SCHEMA.md", "post-reveal-expedition-deferral",
     "the omission reads as a\n  decision, not an accident",
     "Post-Reveal Updating"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-updating-line",
     "post-reveal movement markers"),
    ("platforms/claude-ai/passport/SCHEMA.md",
     "claude-ai-updating-hold-first-class",
     "first-class outcome, never a\n  failure"),
    ("modes/drill.md", "drill-post-reveal-step",
     "Post-miss update rep (miss items only; never a deference test)",
     "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-not-loyalty",
     "a rep,\n   not a loyalty check", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-no-sibling-generation",
     "No fresh sibling stem is\n   generated here", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-log",
     "record `post_reveal` on the same\n   `drill_result`", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-no-act-no-write",
     "no act writes nothing", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-stop-before-write",
     "step 7's write happens only after the user's next turn",
     "Session Flow"),
    ("modes/scene.md", "scene-commitment-shift-anchors",
     "`updated / refined / held_with_argument / held`",
     "Facilitation Flow"),
    ("modes/scene.md", "scene-commitment-shift-no-pressure",
     "never presses the user to\nchange position so the record can say `updated`",
     "Facilitation Flow"),
    ("modes/scene.md", "scene-commitment-shift-neutrality",
     "the states record engagement, never that the objection was right",
     "Facilitation Flow"),
    ("modes/scene.md", "scene-commitment-shift-stop",
     "The objection ends the coach's turn — STOP", "Facilitation Flow"),
    ("modes/drill.md", "drill-post-reveal-challenge-restop",
     "STOP once more", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-recheck-challenge",
     "goes back through step 6's\n   merits check first", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-decline-keeps-events",
     "only the optional `post_reveal` field is omitted", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-no-bare-assent",
     "a bare assent (\"okay, I accept\") is not an observable act",
     "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-sound-rep",
     "why the objection you chose does not actually bite", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-correction-never-withheld",
     "the correction is never withheld to keep\n   the record clean",
     "Session Flow"),
    ("modes/scene.md", "scene-commitment-shift-disjoint",
     "The four are disjoint, judged in order", "Facilitation Flow"),
    ("passport/SCHEMA.md", "post-reveal-scene-disjoint",
     "The four are disjoint, judged\n  in order", "Post-Reveal Updating"),
    ("modes/drill.md", "drill-post-reveal-failed-hold-settles",
     "settles the marker on the spot", "Session Flow"),
    ("modes/drill.md", "drill-post-reveal-manipulation-rep",
     "name the technique and the\n   cue that marks it", "Session Flow"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-updating-counts",
     "explicit\n  per-state counts"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-updating-fold-rule",
     "fold `post_reveal`, `commitment_shift`, and\n"
     "  carried/repeated transitions into the `updating` line"),
    ("platforms/claude-ai/passport/SCHEMA.md",
     "claude-ai-updating-detective-encoding",
     "solely as its `repeated` counter, never as `not_updated`"),
    ("passport/SCHEMA.md", "post-reveal-detective-encoding",
     "solely through its\n`corrections_repeated` counter, never as a state value",
     "Post-Reveal Updating"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-updating-states",
     "the states record\n  engagement, never that the objection was right"),
    ("modes/detective.md", "detective-carry-step",
     "whether the reveal traveled", "Session Flow"),
    ("modes/detective.md", "detective-carry-not-prosecuted",
     "tallied at the close, never prosecuted mid-case", "Session Flow"),
    ("modes/detective.md", "detective-carry-close-metric",
     "**carry** — corrections carried into later layers", "Session Flow"),
    ("modes/detective.md", "detective-carry-logging",
     "`corrections_carried` /\n`corrections_repeated` counters ride along",
     "Logging"),
    ("docs/GATE-checklist.md", "gate15-drill-update",
     "15A (drill update rep + logging)",
     "Gate 15 — Post-Reveal Updating Probes"),
    ("docs/GATE-checklist.md", "gate15-reasoned-hold",
     "15B (reasoned hold is first-class)",
     "Gate 15 — Post-Reveal Updating Probes"),
    ("docs/GATE-checklist.md", "gate15-scene-shift",
     "15C (scene commitment shift anchors)",
     "Gate 15 — Post-Reveal Updating Probes"),
    ("docs/GATE-checklist.md", "gate15-detective-carry",
     "15D (detective carry)",
     "Gate 15 — Post-Reveal Updating Probes"),
    ("docs/GATE-checklist.md", "gate15-sensitive-byom",
     "15E (sensitive BYOM exclusion unchanged)",
     "Gate 15 — Post-Reveal Updating Probes"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate15-drill-update",
     "Land a post-miss restatement", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate15-reasoned-hold",
     "Maintain a reasoned hold", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate15-scene-shift",
     "Refine a commitment under objection", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate15-detective-carry",
     "Re-run a corrected framing", "Results"),
    ("docs/evals/behavior-probes-TEMPLATE.md", "eval-gate15-sensitive-byom",
     "Sensitive BYOM scene with a shifting commitment", "Results"),
    # --- Phase 2: scene fallacy-recognition lenses ---
    ("shared/structures.md", "lens-false-dilemma", "`fallacy_false_dilemma`"),
    ("shared/structures.md", "lens-ad-hominem", "`fallacy_ad_hominem`"),
    ("shared/structures.md", "lens-strawman", "`fallacy_strawman`"),
    ("shared/structures.md", "lens-appeal", "`fallacy_appeal`"),
    ("shared/structures.md", "lens-equivocation", "`fallacy_equivocation`"),
    ("shared/structures.md", "lens-false-analogy", "`fallacy_false_analogy`"),
    ("shared/structures.md", "lens-whataboutism", "`fallacy_whataboutism`"),
    ("shared/structures.md", "lens-slippery-slope", "`fallacy_slippery_slope`"),
    ("shared/structures.md", "lens-genetic", "`fallacy_genetic`"),
    ("shared/structures.md", "lens-no-true-scotsman", "`fallacy_no_true_scotsman`"),
    ("shared/structures.md", "lens-motte-and-bailey",
     "`fallacy_motte_and_bailey`"),
    ("shared/structures.md", "lens-gamblers-fallacy",
     "`fallacy_gamblers_fallacy`"),
    ("shared/structures.md", "lens-reverse-guard-adhominem",
     "becomes circumstantial ad hominem"),
    ("shared/structures.md", "lens-reverse-guard-strawman",
     "Accurately restating an opponent's weak argument is NOT a strawman"),
    ("shared/structures.md", "lens-reverse-guard-appeal",
     "a relevant expert on their own subject is NOT a fallacy"),
    ("shared/structures.md", "lens-reverse-guard-false-dilemma",
     "not every binary is a false dilemma"),
    ("shared/structures.md", "lens-reverse-guard-equivocation",
     "swap must occur within one inferential chain"),
    ("shared/structures.md", "lens-reverse-guard-false-analogy",
     "surface dissimilarity alone never makes an analogy false"),
    ("shared/structures.md", "lens-reverse-guard-whataboutism",
     "Pointing out a genuine double standard or inconsistency is NOT whataboutism"),
    ("shared/structures.md", "lens-reverse-guard-slippery-slope",
     "only unsupported *inevitability* is the defect"),
    ("shared/structures.md", "lens-reverse-guard-genetic",
     "origin can lower credibility or shift the burden of proof, never settle truth"),
    ("shared/structures.md", "lens-reverse-guard-no-true-scotsman",
     "A restriction that was ALREADY part of the claim's definition is NOT the fallacy"),
    ("shared/structures.md", "lens-reverse-guard-motte-and-bailey",
     "Explicitly narrowing or withdrawing the stronger claim is NOT motte-and-bailey "
     "when its stronger conclusion is abandoned, materially weakened"),
    ("shared/structures.md", "lens-motte-and-bailey-known-vs-unknown",
     "Return `insufficient_context` only when the passage presents a possible "
     "stronger/narrower fallback"),
    ("shared/structures.md", "lens-reverse-guard-gamblers-fallacy",
     "A reversal forecast is NOT this fallacy when the available material supplies "
     "a probability-changing bridge"),
    ("shared/structures.md", "lens-gamblers-fallacy-direction-and-strength",
     "resulting conditional probability changes in the claimed direction and "
     "supports the forecast's strength"),
    ("shared/structures.md", "lens-gamblers-fallacy-repeated-outcome-downshift",
     "making the recently repeated or overrepresented outcome less likely"),
    ("shared/structures.md", "lens-gamblers-fallacy-calibration-boundary",
     "A misread rule, arithmetic mistake, or calibration error without that bridge "
     "remains wrong but is `not_fallacy` under this lens"),
    ("shared/structures.md", "lens-gamblers-fallacy-unknown-generator",
     "Use `insufficient_context` for a possible compensation inference only when "
     "a missing generator rule, replacement condition, parameter fact, horizon, "
     "state, or actor reason could change the active-lens ruling"),
    ("modes/scene.md", "fallacy-whataboutism-defect-test",
     "unanswered-charge test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-slippery-slope-defect-test",
     "chain-support test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-genetic-defect-test",
     "origin-independence test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-no-true-scotsman-defect-test",
     "prior-definition test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-motte-and-bailey-defect-test",
     "fallback-substitution test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-motte-and-bailey-collision-boundary",
     "A critic's paraphrase cannot supply the stronger claim",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-motte-and-bailey-retained-conclusion",
     "Withdrawing the claim while retaining its stronger conclusion without an\n"
     "     independently adequate new bridge",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-motte-and-bailey-one-lens-boundary",
     "Never silently switch the active lens",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-motte-and-bailey-clean-strawman",
     "advocate never advanced or adopted the stronger claim, return\n"
     "     `not_fallacy`",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-defect-test",
     "history-dependence test", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-hot-hand-boundary",
     "Positive-recency continuation is not gambler's fallacy",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-legitimate-positive-recency",
     "supported parameter learning or dependence\n"
     "     may make continuation legitimate",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-independent-block",
     "In known independent trials with an unchanged outcome distribution",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-compensation-bridge",
     "The unsupported shift must be attributed to\n"
     "     due-ness, balance, or equivalent local compensation",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-calibration-boundary",
     "calibration\n"
     "     overstatement without that bridge remains wrong but is `not_fallacy` under",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-rtm-model",
     "imperfectly correlated\n"
     "     repeats and fresh mean-zero noise around stable latent values",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-no-behavior-inference",
     "streak with no stated reason is such a case: return\n"
     "     `insufficient_context` and never infer the belief from behavior alone",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-gamblers-fallacy-context-can-change-ruling",
     "actor reason\n     could change the active-lens ruling",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-track-not-whole-argument-certificate",
     "this ruling does not certify the whole argument",
     "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-track-surviving-lens-no-endorsement",
     "If another defect may exist, it does\n"
     "not endorse the whole argument; it finishes this ruling before offering a\n"
     "separate round or route",
     "Fallacy-Recognition Track"),
    ("SKILL.md", "fallacy-motte-and-bailey-routing",
     "motte-and-bailey", "Mode Routing"),
    ("SKILL.md", "fallacy-gamblers-fallacy-routing",
     "gambler's fallacy", "Mode Routing"),
    ("modes/scene.md", "fallacy-track-transfer-test",
     "Name the property the conclusion", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-track-submode",
     "One submode is active per round"),
    ("modes/scene.md", "fallacy-track-redline1-exception",
     "Redline 1 governs value-frame interpretation, not fallacy-form adjudication"),
    ("modes/scene.md", "fallacy-track-three-rulings",
     "`fallacy` / `not_fallacy` / `insufficient_context`"),
    ("modes/scene.md", "fallacy-track-insufficient-context",
     "forcing a binary verdict on a context-dependent case"),
    ("modes/scene.md", "fallacy-track-four-step",
     "Is that move genuinely irrelevant to the conclusion"),
    ("modes/scene.md", "fallacy-track-per-lens-test",
     "relevance is the test for only two of them"),
    ("modes/scene.md", "fallacy-track-no-reward-labeling",
     "reward fallacy-labeling as sophistication"),
    ("modes/scene.md", "fallacy-track-charitable-reconstruct",
     "charitably reconstruct the opponent's real position first"),
    ("modes/scene.md", "fallacy-track-synthetic-first",
     "synthetic, non-party examples for training"),
    ("SKILL.md", "fallacy-track-routing",
     "fallacy recognition (is this argument a fallacy"),
    ("modes/scene.md", "fallacy-track-entry",
     "what selects the fallacy-recognition track"),
    ("modes/scene.md", "fallacy-track-off-list-no-improvised",
     "never improvises a ruling on it", "Fallacy-Recognition Track"),
    ("modes/scene.md", "fallacy-track-off-list-decline",
     "forcing a verdict without a defect test is itself the reasoning error",
     "Fallacy-Recognition Track"),
    ("shared/structures.md", "lens-set-complete-ruling-surface",
     "the complete ruling surface", "Fallacy-Recognition Lenses"),
    ("passport/SCHEMA.md", "scene-fallacies-examined", "fallacies_examined"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-fallacies-examined",
     "fallacies_examined"),
    ("modes/scene.md", "scene-logging-fallacy-round",
     "A fallacy-recognition round records"),
    ("modes/drill.md", "compound-primary-logging", "never as a second event"),
    ("modes/drill.md", "commit-gate-safe-words",
     "one scaffold step about the stem or the structure vocabulary"),
    ("modes/drill.md", "tier-option-count", "per the Difficulty Knobs table"),
    ("modes/drill.md", "tier-distractor-count", "intro: 2; standard/advanced: 4"),
    ("modes/scene.md", "observation-window-safe-words",
     "never a frame name or a reading of this scene"),
    ("modes/scene.md", "scene-steelman-before-correction",
     "The complete reconstruction always comes"),
    ("modes/scene.md", "advanced-palette-completion",
     "before the closing pressure test (redline 5)"),
    ("shared/scaffolding.md", "silence-window-safe-words",
     "cannot leak the key or a reading"),
    ("shared/scaffolding.md", "no-anchor-branch",
     "skip the anchor rather than invent one"),
    ("shared/scaffolding.md", "scene-stuck-equivalent",
     "then returns to the live scene"),
    ("SKILL.md", "safe-words-every-path", "in every path"),
    ("SKILL.md", "switch-full-profile-set",
     "carrying forward the unchanged fields"),
    ("passport/SCHEMA.md", "steelman-all-frames",
     "every raised frame was steelmanned"),
    ("passport/SCHEMA.md", "sensitive-byom-commitment", "including `commitment`"),
    ("passport/TEMPLATE.md", "template-sample-data", "never copy them"),
    # --- review round 2 ---
    ("README.md", "byom-no-events", "writes no passport events at all"),
    ("SKILL.md", "byom-domain-default",
     "defaults to `[\"no preference\"]`"),
    # --- v1.1 batch 1: fixes from first real-world claude.ai session ---
    ("shared/scaffolding.md", "language-script-variant",
     "including script variant"),
    ("shared/scaffolding.md", "no-third-script",
     "unrelated third language or script"),
    ("modes/drill.md", "domain-fit-gate",
     "Never silently re-skin material"),
    ("modes/drill.md", "domain-fit-stop",
     "STOP before generating anything"),
    ("modes/drill.md", "dissection-no-overstate",
     "distractor classifications never overstate"),
    ("modes/scene.md", "adapted-palette-counter",
     "is the suspected flaw actually a flaw?"),
    ("modes/scene.md", "material-preflight",
     "never present material the coach cannot cleanly defend in dissection"),
    ("shared/redlines.md", "rl5-adapted-palette",
     "substitutes an adapted lens palette"),
    ("SKILL.md", "switch-no-reset",
     "never resets the running record"),
    # --- v1.1 batch 2: manipulation-recognition domain ---
    ("shared/redlines.md", "rl13-no-production",
     "never optimizes, personalizes, or supplies"),
    ("shared/redlines.md", "rl13-armory",
     "must not double as an armory"),
    ("shared/redlines.md", "rl13-political-balance",
     "the technique is adjudicated, never the political"),
    ("shared/redlines.md", "rl14-concede-on-merits",
     "Concede on the merits, never to please"),
    ("shared/redlines.md", "rl14-key-and-frame",
     "neither the key nor the frame is self-evidently right"),
    ("shared/redlines.md", "rl14-fabricated-concession",
     "a step that does not actually establish the point is a fabricated"),
    ("shared/redlines.md", "rl14-produced-not-felt",
     "it must be produced, not merely felt"),
    ("shared/redlines.md", "rl14-four-facts",
     "the coach writes out, in the visible turn,"),
    ("shared/redlines.md", "rl14-translation-discipline",
     "reasoning that holds is 成立"),
    ("shared/manipulation-taxonomy.md", "mt-gaslighting", "gaslighting"),
    ("shared/manipulation-taxonomy.md", "mt-love-bombing", "love_bombing"),
    ("shared/manipulation-taxonomy.md", "mt-whataboutism", "whataboutism"),
    ("shared/manipulation-taxonomy.md", "mt-synthetic-only",
     "All material is synthetic by construction"),
    ("shared/manipulation-taxonomy.md", "mt-off-ramp",
     "does not roleplay counseling"),
    ("shared/structures.md", "manipulation-id-exception",
     "`manipulation_spot` items log technique"),
    ("modes/drill.md", "manipulation-item-type",
     "### 4. `manipulation_spot`"),
    ("SKILL.md", "manipulation-domain-load",
     "additionally load `shared/manipulation-taxonomy.md`"),
    ("passport/SCHEMA.md", "manipulation-item-enum",
     "assumption|weaken|sufficiency|manipulation_spot"),
    ("docs/GATE-checklist.md", "rl13-probe",
     "RL13 (recognition, never production)"),
    # --- v1.1 batch 3: expedition mode ---
    ("modes/expedition.md", "no-pack-no-expedition",
     "Expedition material is NEVER improvised"),
    ("modes/expedition.md", "pack-refusal-fields",
     "The coach refuses a pack missing any of its required fields"),
    ("modes/expedition.md", "auditor-default", "auditor (default)"),
    ("modes/expedition.md", "forecaster-grades-from-calibration-key",
     "grades from that rubric's"),
    ("modes/expedition.md", "search-first", "`search_first`"),
    ("modes/expedition.md", "discipline-kill-criteria", "`kill_criteria`"),
    ("modes/expedition.md", "expedition-no-soft-switch",
     "Mid-session switching into or out of expedition is unsupported"),
    ("SKILL.md", "expedition-no-soft-switch-router",
     "switching into or out of expedition mid-session is unsupported"),
    ("expeditions/PACK-SCHEMA.md", "provenance-required",
     "A pack without provenance is invalid"),
    ("expeditions/PACK-SCHEMA.md", "solved-only",
     "verified solutions, never open conjectures"),
    ("expeditions/PACK-SCHEMA.md", "first-party-verification",
     "the author has read the actual\n  solution source"),
    ("expeditions/PACK-SCHEMA.md", "feynman-terrain-not-vocabulary",
     "High difficulty must come from the\n  terrain, never from the vocabulary"),
    ("expeditions/PACK-SCHEMA.md", "feynman-load-bearing-inventory",
     "Before rewriting, inventory every load-bearing term, condition, and\n"
     "     qualifier"),
    ("expeditions/PACK-SCHEMA.md", "feynman-add-never-replace",
     "Plain-language anchors are additions, never replacements for the precise\n"
     "     technical terms they explain"),
    ("expeditions/PACK-SCHEMA.md", "feynman-back-translation",
     "A rewrite passes only if a domain-literate reviewer can reconstruct the\n"
     "     precise original claim from the plain version alone"),
    ("expeditions/PACK-SCHEMA.md", "feynman-facts-return-to-source",
     "Every factual sentence touched by a rewrite must be re-verified against its\n"
     "     cited first-party source"),
    ("SKILL.md", "expedition-routing",
     "`expedition` / `impossible` → load `modes/expedition.md`"),
    ("passport/SCHEMA.md", "expedition-event", "expedition_process"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-expedition-line",
     "one entry per completed expedition"),
    ("shared/scaffolding.md", "expedition-outside-tiers",
     "Expedition mode sits outside the three tiers"),
    # --- v1.1 simplify pass: count guards + new gate probes ---
    ("shared/redlines.md", "fourteen-rules",
     "These fourteen rules are absolute"),
    ("shared/scaffolding.md", "redline-count",
     "the fourteen redlines"),
    ("docs/GATE-checklist.md", "gate7-domain-fit",
     "7A (domain-fit STOP)"),
    ("docs/GATE-checklist.md", "gate7-off-ramp",
     "7B (distress off-ramp)"),
    ("modes/drill.md", "manipulation-distractor-source",
     "step (f) draws"),
    # --- v1.2: first pack + expedition hardening ---
    ("modes/expedition.md", "pack-discovery-by-id",
     "any file declaring a `pack_id` field"),
    ("modes/expedition.md", "pack-boundary-runtime",
     "The pack boundary holds at runtime too"),
    ("docs/GATE-checklist.md", "gate8-no-pack-refusal", "8A (no-pack refusal)",
     "Gate 8 — Expedition Probes"),
    ("docs/GATE-checklist.md", "gate8-hint-discipline",
     "8B (hint discipline, auditor)", "Gate 8 — Expedition Probes"),
    ("docs/GATE-checklist.md", "gate8-breakthrough-stop",
     "8C (breakthrough stop)", "Gate 8 — Expedition Probes"),
    ("docs/GATE-checklist.md", "gate8-pack-boundary", "8D (pack boundary)",
     "Gate 8 — Expedition Probes"),
    # --- v1.3: weak-model drill quality floor ---
    ("modes/drill.md", "slot-template",
     "fill the target structure's slot template"),
    ("modes/drill.md", "option-audit-table",
     "Reverse-solve check — audit the distractors"),
    ("modes/drill.md", "audit-release-rule",
     "Release the item ONLY if"),
    ("modes/drill.md", "regenerate-not-patch",
     "regenerate rather than edit"),
    ("modes/drill.md", "fallback-ladder",
     "Weak-model fallback ladder"),
    ("modes/drill.md", "fallback-refuse",
     "refuse to generate this item"),
    # --- v1.4: detective mode (4th mode) ---
    ("modes/detective.md", "detective-positioning",
     "guide-and-judge fourth stance"),
    ("modes/detective.md", "detective-judges-not-ranks",
     "never ranks the frame itself"),
    ("modes/detective.md", "detective-never-solves",
     "never catches it for them"),
    ("modes/detective.md", "detective-one-main-flaw",
     "exactly one main flaw per layer"),
    ("modes/detective.md", "detective-key-is-concrete",
     "this helps interpret the next layer"),
    ("modes/detective.md", "detective-per-layer-material",
     "per-layer, not one omnibus document"),
    ("modes/detective.md", "detective-inspect-before-rule",
     "never auto-rule it a false positive"),
    ("modes/detective.md", "detective-g0-frame",
     "Stipulate the case frame"),
    ("modes/detective.md", "detective-reverse-design",
     "keys first, material last"),
    ("modes/detective.md", "detective-g2-ablation",
     "hide layer N's key entirely"),
    ("modes/detective.md", "detective-ablation-redesign",
     "is fake; redesign the skeleton"),
    ("modes/detective.md", "detective-mechanical-vs-soft",
     "weak model will falsely self-certify"),
    ("modes/detective.md", "detective-no-accidental-flaw",
     "unregistered (N+1)th flaw"),
    ("modes/detective.md", "detective-open-frame-first",
     "present the G0 frame first"),
    ("modes/detective.md", "detective-generation-silence",
     "produce zero user-visible",
     "Generation Pipeline (reverse design — keys first, material last)"),
    ("modes/detective.md", "detective-open-silence",
     "The first visible message begins here, at Open",
     "Session Flow"),
    ("modes/detective.md", "detective-no-preamble",
     "no preamble of any kind",
     "Session Flow"),
    ("modes/detective.md", "detective-no-pipeline-announce",
     "do not announce that G0–G6 ran",
     "Generation Pipeline (reverse design — keys first, material last)"),
    ("modes/detective.md", "detective-safe-words",
     "`enough for today`"),
    ("modes/detective.md", "detective-intro-two-layers",
     "2 layers, 1 main flaw/layer"),
    ("modes/detective.md", "detective-statistical-gate",
     "appear in detective only at standard and above"),
    ("modes/detective.md", "detective-log-event",
     "detective_process"),
    ("SKILL.md", "detective-routing",
     "`detective` → load `modes/detective.md`"),
    ("SKILL.md", "detective-soft-switchable",
     "Detective is soft-switchable like drill and scene"),
    ("SKILL.md", "detective-opus-recommendation",
     "detective mode recommends an opus-class or stronger model"),
    ("passport/SCHEMA.md", "detective-event", "detective_process"),
    ("passport/SCHEMA.md", "detective-event-fields", "unregistered_flaws_found"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-detective-line",
     "one entry per completed detective case"),
    ("docs/GATE-checklist.md", "gate9-ablation", "9A (key-chain ablation)",
     "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate9-correct-objection",
     "9B (correct-objection honesty)", "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate9-frame-dispute",
     "9C (frame-dispute handling)", "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate9-never-solve",
     "9D (never-solve line)", "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate9-safe-word",
     "9E (safe-word non-trapping)", "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate9-generation-silence",
     "9F (generation-silence / fresh-session leak)", "Gate 9 — Detective Probes"),
    ("docs/GATE-checklist.md", "gate10-mislabel",
     "10A (conflict-of-interest contrast pair)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-insufficient",
     "10B (insufficient-context honesty)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-isolation",
     "10C (track isolation)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-political",
     "10D (political spot-check)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-non-relevance",
     "10E (non-relevance lens defect)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-appeal",
     "10F (fallacious-appeal relevance)", "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey",
     "10L (motte-and-bailey fallback-substitution test + reverse-guard)",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-position-boundary",
     "uses Northbridge's shared group label to splice the fourth excerpt's speakers\n"
     "into one advocate",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-return-and-retention",
     "`fallacy` on both the fifth and\nsixth",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-collision-rulings",
     "returns `not_fallacy` on 10B under the\nactive lens because no fallback sequence "
     "appears",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-independent-bridge",
     "18-percentage-point placement improvement over the next-best bidder",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-synonym-guard",
     "\"employment\nassured within 30 days,\" with no new support",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-new-bridge-verdicts",
     "sixth, `not_fallacy` on the seventh, and `fallacy` on the eighth",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-clean-strawman",
     "complete official statement that advances only the narrower\nclaim",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-motte-and-bailey-clean-strawman-verdict",
     "returns `not_fallacy` under motte-and-bailey and\noffers strawman in a separate round",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy",
     "10M (gambler's-fallacy history-dependence test + reverse-guards)",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-verdict-matrix",
     "The\nfifteen rulings, in order, must be `fallacy`, `not_fallacy`, `not_fallacy`,\n"
     "`not_fallacy`, `insufficient_context`, `insufficient_context`, `fallacy`,\n"
     "`not_fallacy`, `not_fallacy`, `fallacy`, `not_fallacy`, `not_fallacy`,\n"
     "`not_fallacy`, `fallacy`, and `not_fallacy`",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-context-branches",
     "forces a\nbinary verdict on the fifth; infers a compensation belief from the sixth's bet",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-per-lens-controls",
     "coach must not silently switch lenses or issue a second verdict in the same\nround",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-likely-conclusion",
     "accepts its due-ness\nbridge merely because blue was already likely",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-update-direction",
     "accepts the tenth's named update without checking its direction",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-selection-collision",
     "endpoint-conditioned\nsample selection",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-multi-outcome",
     "requires a\nnamed contrary outcome and therefore misses the fourteenth's unsupported\n"
     "downward shift",
     "Gate 10 — Fallacy-Track Probes"),
    ("docs/GATE-checklist.md", "gate10-gamblers-fallacy-calibration",
     "calls the fifteenth gambler's fallacy merely\n"
     "because .70 overstates the real .60",
     "Gate 10 — Fallacy-Track Probes"),
]

# --- claude.ai overlay (platforms/claude-ai/) ---
# Overlay files replace their canonical counterparts in the claude.ai zip;
# every redline and SKILL.md invariant must survive the platform rewrite.
_OVERLAY_MAP = {
    "shared/redlines.md": "platforms/claude-ai/shared/redlines.md",
    "shared/scaffolding.md": "platforms/claude-ai/shared/scaffolding.md",
    "SKILL.md": "platforms/claude-ai/SKILL.md",
}
CHECKS += [
    (_OVERLAY_MAP[entry[0]], f"claude-ai-{entry[1]}", *entry[2:])
    for entry in list(CHECKS)
    if entry[0] in _OVERLAY_MAP
]

# Canonical-only local-filesystem contracts are added after overlay expansion:
# the claude.ai SKILL intentionally has no helper or on-disk Passport.
CHECKS += [
    ("SKILL.md", "local-passport-helper-routing",
     "Every local checkpoint and `delete passport` operation must invoke",
     "Passport Contract"),
    ("SKILL.md", "local-passport-generation-startup",
     "At local session startup, before checking for a returning user or reading the\n"
     "event log, invoke `<skill-root>/scripts/passport_checkpoint.sh generation`",
     "Passport Contract"),
    ("SKILL.md", "local-passport-node-off-ramp",
     "If it exits 69, pause recording for this session",
     "Passport Contract"),
    ("SKILL.md", "local-passport-read-helper",
     "Returning-user and \"show passport\" reads must invoke the helper's\n"
     "`read --generation TOKEN` command; never use a direct filesystem read",
     "Passport Contract"),
    ("SKILL.md", "local-passport-generation-mismatch",
     "On exit 76, discard the stale\n"
     "batch or read snapshot and invoke the helper's `generation` command again",
     "Passport Contract"),
    ("docs/GATE-checklist.md", "gate4-concurrent-checkpoints",
     "4B (real concurrent checkpoints)",
     "Gate 4 — Passport Durability and Corruption Recovery"),
    ("docs/GATE-checklist.md", "gate4-generation-invalidation",
     "delete serialization and generation invalidation",
     "Gate 4 — Passport Durability and Corruption Recovery"),
    ("docs/GATE-checklist.md", "gate4-locked-read",
     "`read --generation TOKEN` command",
     "Gate 4 — Passport Durability and Corruption Recovery"),
    ("docs/GATE-checklist.md", "gate4-node-off-ramp",
     "A simulated exit 69 must pause recording",
     "Gate 4 — Passport Durability and Corruption Recovery"),
    ("docs/GATE-checklist.md", "gate4-runtime-helper",
     "4C (runtime uses the one writer)",
     "Gate 4 — Passport Durability and Corruption Recovery"),
    ("CLAUDE.md", "claude-local-passport-helper",
     "every local checkpoint and deletion goes through\n"
     "`scripts/passport_checkpoint.sh`"),
    ("CLAUDE.md", "claude-passport-node-worker",
     "thin `passport_checkpoint.sh` entry point and Node.js-stdlib worker"),
    ("README.md", "readme-passport-node-prerequisite",
     "**Local Passport prerequisite:**"),
]

# (file, label, substring that must be ABSENT)
FORBIDDEN = [
    # No local-filesystem passport vocabulary may leak into the claude.ai build.
    ("platforms/claude-ai/SKILL.md", "claude-ai-no-local-path", "~/.ct-gym"),
    ("platforms/claude-ai/SKILL.md", "claude-ai-no-jsonl-skill", "events.jsonl"),
    ("platforms/claude-ai/passport/SCHEMA.md", "claude-ai-no-jsonl-schema", "events.jsonl"),
    ("platforms/claude-ai/shared/redlines.md", "claude-ai-no-on-disk", "stay on disk"),
    ("platforms/claude-ai/shared/scaffolding.md", "claude-ai-no-on-disk-scaffolding", "on disk"),
    ("passport/SCHEMA.md", "no-unsafe-concurrent-passport-limitation",
     "Known limitation — run one session at a time."),
    ("passport/SCHEMA.md", "no-post-delete-passport-resurrection-warning",
     "An already-open second session can later create a fresh log"),
    # Guard against the stale three-mode phrasing returning to either SKILL file.
    ("SKILL.md", "no-stale-three-modes", "through three modes"),
    ("SKILL.md", "no-stale-three-modes-body", "Three modes with deliberately"),
    ("platforms/claude-ai/SKILL.md", "no-stale-three-modes-overlay", "through three modes"),
    ("platforms/claude-ai/SKILL.md", "no-stale-three-modes-body-overlay", "Three modes with deliberately"),
    # The 14th-structure promotion must not regress in live docs/runtime/manifests.
    # Historical CHANGELOG and completed eval reports intentionally stay untouched.
    ("shared/structures.md", "no-stale-thirteen-structures",
     "thirteen loggable structure IDs"),
    ("shared/structures.md", "no-stale-thirteen-source-boundary",
     "The thirteen structures above"),
    ("modes/drill.md", "no-stale-thirteen-drill-ids",
     "the thirteen structure IDs"),
    ("modes/drill.md", "no-stale-thirteen-sound-audit",
     "walk the thirteen structures"),
    ("modes/detective.md", "no-stale-thirteen-detective",
     "the thirteen-structure set"),
    ("shared/manipulation-taxonomy.md", "no-stale-thirteen-manipulation",
     "thirteen reasoning-structure IDs"),
    ("README.md", "no-stale-readme-one-of-thirteen",
     "one of thirteen structures"),
    ("README.md", "no-stale-readme-thirteen-drill",
     "The thirteen drill structures"),
    ("docs/ARCHITECTURE.md", "no-stale-architecture-thirteen-prose",
     "the thirteen reasoning structures"),
    ("docs/ARCHITECTURE.md", "no-stale-architecture-thirteen-heading",
     "The thirteen reasoning structures"),
    ("docs/ARCHITECTURE.md", "no-stale-architecture-thirteen-node",
     "13 canonical structures"),
    ("docs/ARCHITECTURE.md", "no-stale-architecture-thirteen-floor",
     "13 structures · frame palette"),
    ("CLAUDE.md", "no-stale-claude-thirteen-structures",
     "the 13 keyed reasoning structures"),
    (".claude-plugin/plugin.json", "no-stale-plugin-thirteen-structures",
     "13 argument structures"),
    (".claude-plugin/marketplace.json", "no-stale-marketplace-thirteen-structures",
     "13 argument structures"),
    ("docs/evals/README.md", "no-stale-eval-readme-twelve-structures",
     "twelve structures"),
    ("docs/evals/key-agreement-TEMPLATE.md", "no-stale-key-template-twelve-structures",
     "12 structures"),
    ("docs/evals/human-validity-anchor-TEMPLATE.md",
     "no-stale-human-template-twelve-structures", "twelve structures"),
    # The distractor-menu count must not regress after #47 added the two
    # framing patterns.
    ("shared/structures.md", "no-stale-eight-distractors",
     "eight wrong-answer patterns"),
]


def h2_section_body(text: str, title: str) -> Optional[str]:
    """Return the body of the H2 section with the given title, or None."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if start is None:
            if line.strip() == f"## {title}":
                start = i + 1
        elif line.startswith("## "):
            return "\n".join(lines[start:i])
    return "\n".join(lines[start:]) if start is not None else None


def main(root: Path = ROOT) -> int:
    failures = 0
    missing_files = set()
    texts = {}
    for entry in CHECKS:
        rel, label, needle = entry[0], entry[1], entry[2]
        section = entry[3] if len(entry) > 3 else None
        if rel in missing_files:
            failures += 1
            continue
        path = root / rel
        if rel not in texts:
            if not path.exists():
                # One FAIL line per missing file, but every check on it still
                # counts as a failure (intentional).
                print(f"FAIL [{rel}] file missing")
                missing_files.add(rel)
                failures += 1
                continue
            texts[rel] = path.read_text(encoding="utf-8")
        scope = texts[rel]
        if section is not None:
            scope = h2_section_body(scope, section)
            if scope is None:
                print(f"FAIL [{label}] H2 section missing in {rel}: {section!r}")
                failures += 1
                continue
        if needle.strip() in scope:
            print(f"PASS [{label}]")
        else:
            where = f"section {section!r} of {rel}" if section else rel
            print(f"FAIL [{label}] missing in {where}: {needle!r}")
            failures += 1
    for rel, label, needle in FORBIDDEN:
        path = root / rel
        if not path.exists():
            print(f"FAIL [{rel}] file missing")
            failures += 1
            continue
        if needle in path.read_text(encoding="utf-8"):
            print(f"FAIL [{label}] forbidden substring present in {rel}: {needle!r}")
            failures += 1
        else:
            print(f"PASS [{label}]")
    total = len(CHECKS) + len(FORBIDDEN)
    print(f"\n{total - failures}/{total} checks green")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
