export const supportedLocales = Object.freeze(['zh-TW', 'en'])

export const resolveLocale = (value) => String(value || '').toLowerCase().startsWith('zh') ? 'zh-TW' : 'en'

const zhTW = {
  meta: {
    title: '懷疑所 Casebook｜每日推理練習與四種批判思考示範',
    description: '用復古偵探遊戲練習批判思考。可切換台灣繁體中文與英文，包含推理快問、情境觀察、科學預測與案件稽核。',
    noscript: '這個互動示範需要開啟 JavaScript。',
  },
  language: { label: '語言', zh: '中文', en: 'EN', changed: '已切換成台灣繁體中文' },
  common: {
    close: '關閉', back: '返回玩法選擇', exitMode: '離開這個模式', exitDaily: '離開今日案件',
    progress: '進度', fixedDemo: '固定示範', fixedCase: '固定案例', continue: '繼續', replay: '再玩一次',
    xpEarned: '本輪獲得', on: '開啟', off: '關閉', retry: '重試',
  },
  brand: { seal: '疑', name: '懷疑所', subtitle: 'CASEBOOK' },
  audio: {
    code: '音效控制台',
    musicOn: '關閉背景音樂', musicOff: '開啟背景音樂', sfxOn: '關閉答題音效', sfxOff: '開啟答題音效',
    settings: '音訊設定', title: '音訊設定', music: '背景音樂', musicDescription: '原創復古懸疑配樂；第一次操作頁面後才會播放。',
    volume: '音樂音量', sfx: '答題音效', sfxDescription: '翻紙、發現線索、答對與修正提示。',
    browserNote: '瀏覽器會遵守自動播放限制；切到其他分頁時，音樂會暫停。',
  },
  stats: {
    label: '玩家進度', streak: '連續練習', day: '天', clues: '找到的線索', rank: '調查員等級',
    passport: '護照', passportLabel: '開啟調查員護照', sessions: '完成次數', level: '第 {level} 級', toNext: '再 {xp} XP 升級',
  },
  home: {
    practice: '今日練習', overline: '選擇練習方式', titleBefore: '今晚，你想從哪一扇門', titleEmphasis: '開始調查？',
    intro: '先選想調查的領域，再進入對應的每日案件或雙語固定示範。每個模式都會先說明題材、玩法與限制。',
    circuitLabel: '今日四種模式進度', circuit: '今日練習',
    circuitDone: '四種模式今天都玩過了；你仍可不限次重玩。',
    circuitOpen: '完成任一模式就能延續連續練習；四種模式都可以自由重玩。',
    sectionCode: '四種模式 · 四種思考姿勢', sectionTitle: '選擇今晚的案件',
    sectionNote: '這些是固定、可重玩的雙語示範，不等同於 CLI／Skill 的動態完整流程。',
    completed: '今天玩過 · 可重玩', routeLabel: '三種使用方式', routeButton: '查看差異與登入限制',
    routesSummary: 'CLI、Skill ZIP 與網頁遊戲是三個並行入口；完整功能與帳號限制各不相同。',
    routes: {
      cli: '完整四種模式、動態 AI 與本機護照。',
      zip: '上傳到支援的平台，以對話方式使用。',
      web: '給不熟 CLI 的人使用；固定示範加上選配的每日案件。',
    },
    privacyFooter: '4 個雙語固定示範 + 選配的每日案件 API · 不上傳自由文字',
  },
  domains: {
    code: '第一步（共兩步）· 選擇案件領域', title: '你今晚想調查哪一類問題？',
    intro: '選完領域後，第二步才會顯示對應的案例與模式。選「綜合案件」可查看全部四種模式。',
    chooseFirst: '先選一個領域；選好後，案件會立刻在下方開放。', complete: '第一步完成',
    selected: '已選擇：{domain}', stepTwo: '第二步（共兩步）· 選擇練習模式', change: '切換領域', available: '{count} 個可玩示範',
    labels: { all: '綜合案件', education: '教育', health: '健康與醫療', public: '公共議題', science: '科學與科技', work: '職場與商業' },
    descriptions: {
      all: '混合題材，四種模式全部開放。', education: '檢查課程成效與評量證據。', health: '看懂風險、檢測與基準率。',
      public: '新聞判讀、交通安全與公共決策。', science: '預測科學突破的幅度與邊界。', work: '稽核 AI 成效報告與商業數據。',
    },
    drillExcerpt: '{domain}目前有 {count} 題固定入門練習。作答後會逐項說明。', drillMechanic: '{count} 題領域示範',
    drillBoundary: '這是 {count} 題固定入門示範；作答後會逐項說明。動態出題與挑戰答案請使用 CLI／Skill。',
    noCases: '這個領域目前還沒有可玩的固定案例。',
  },
  daily: {
    labels: { drill: '快問', scene: '情境觀察', expedition: '科學預測', detective: '案件稽核' },
    loading: '電報正在穿過霧港，今日案件就快送到了。',
    readyScene: '從六個角度看同一個情境；系統不會把立場判成對錯。',
    readyChoice: '{count} 份資料；作答後由伺服器回傳這次需要的解析。',
    complete: '今天的案件已完成。你可以重玩，但不會重複取得獎勵。',
    unavailableCase: '題目預覽已送達，但伺服器解析尚未啟用；四種固定示範仍可正常遊玩。',
    unavailable: '每日案件服務尚未啟用；四種固定示範仍可正常遊玩。',
    localeUnavailable: '今日案件目前只有台灣繁中版。你可以切回中文，或先玩下方四種英文示範。',
    reopen: '重玩今日案件', open: '開始今日案件', receiving: '接收案件中', disabled: '解析尚未啟用', retryLabel: '重新接收今日案件',
    connecting: '連線中', timezone: 'Asia/Taipei 每日更新', preview: '公開預覽／解析服務未連線', closed: '案件完成 · 可重玩',
    duration: '每天一案 · 約 3–7 分鐘', arriving: '今日案件正在送達', mode: '模式', waiting: '等待接收', ruling: '解析',
    sealed: '伺服器回傳', neutral: '不評分流程', notEnabled: '未啟用', dispatch: '每日案件',
    publicPrivate: '每日案件 · 公開題目／伺服器回傳', answerOnly: '只會送出選項代號', checking: '伺服器核對中…',
    sceneExcerpt: '每日情境節錄 · 不評分立場', sceneRead: '先讀完情境，不急著下結論', sceneNoText: '每日節錄不會上傳自由文字', firstAngle: '查看第一個角度',
    caseExpired: '台北時間已經換日。請回首頁重新接收今日案件。',
    rulingError: '伺服器暫時沒有回應。你的選擇仍留在本頁，可以再試一次。',
    hitAnnounce: '答對，獲得 {xp} XP', missAnnounce: '解析已更新，獲得 {xp} XP', expiredAnnounce: '今日案件已換日', errorAnnounce: '伺服器暫時沒有回應',
  },
  brief: {
    route: '本次內容', duration: '預估時間', source: '內容依據', chooseAnother: '換一個模式', enter: '開始{mode}',
    caseFrameTitle: '這個案件要檢查什麼？', frameClaim: '公司主張', frameSuccess: '怎樣才算成立', frameStandard: '判斷標準', frameEvidence: '可用資料',
    boundaries: {
      drill: '這是三題固定入門示範。每題只有一個可辯護答案；作答後會逐項說明。動態出題與挑戰答案請使用 CLI／Skill。',
      scene: '這個模式不評分你的立場。燈亮只代表你已從一個角度看過情境，不代表系統同意你的價值判斷。',
      expedition: '這是 AlphaFold 2 在 CASP14 的「預測者」固定節錄。目標是校準預測，不是解出蛋白質，也不是完整的遠征模式。',
      detective: '這是兩步入門案件稽核：第一步取得一個數值，第二步必須用到它。自由輸入、額外漏洞與答案質疑仍需使用 CLI／Skill。',
    },
  },
  play: {
    sealed: '資料還沒拆封', inspect: '查看資料', hint: '給我一點提示', lockPrediction: '鎖定預測', lockAnswer: '鎖定答案',
    fixedVersion: '固定示範 · Skill {version}', hit: '答對', review: '再想一下', answerIs: '答案是 {answer}', keyFound: '找到關鍵推論',
    explainAgain: '再說明一次', summary: '查看本輪整理', next: '下一題',
    practiceNote: '答錯不扣生命；解析會把錯誤變成下次可用的線索。',
    forecastNote: '這裡只記錄預測是否校準，不代表你解出了科學問題。',
    challengeNote: '不同意解析嗎？CLI／Skill 版可以直接提出反駁；固定網頁示範只能提供事先寫好的說明。',
    earned: '{result}，獲得 {xp} XP', unlocked: '已解鎖解析',
    whyOptions: '逐項解析', chosen: '你的選擇', correct: '正解', distractor: '其他選項',
  },
  scene: {
    observeCode: '先觀察，再分析', observeTitle: '把你看到的事實寫下來',
    observeBody: '先不用下結論，也不會顯示分析角度。請把文字中確實出現的內容，用自己的話記下來。',
    observationLabel: '我的第一眼觀察', observationPlaceholder: '用自己的話記下來……',
    localOnly: '文字只保留在這個分頁，不會寫入護照。', saveObservation: '記下觀察',
    angleCode: '角度', reviewed: '已看過這個角度', noPreferred: '沒有隱藏的標準立場', nextSelf: '回頭檢查自己的看法', nextAngle: '下一個角度',
    angleHint: '這個角度在看什麼？', reviewAngle: '看完這個角度',
    cameraCode: '回頭檢查自己的看法', cameraTitle: '你目前比較傾向哪一種看法？',
    cameraBody: '這不是測驗。先選一個暫時立場，再寫下它可能忽略了什麼。', blindspotLabel: '這個看法可能忽略了……',
    blindspotPlaceholder: '請寫下一個可能的盲點……', revisable: '有新證據時，暫時立場可以改變。', savePosition: '記下暫時判斷',
    commitmentCode: '做出決定', commitmentTitle: '如果今晚由你決定，你會怎麼做？',
    commitmentBody: '選一個你目前願意負責的做法，再寫下理由。系統會提出一個有力的反對意見。',
    reasonLabel: '我的理由', reasonPlaceholder: '我選這個做法，因為……', noPreference: '選項不代表系統偏好', pressure: '查看反對意見',
    objectionCode: '一個有力的反對意見', objectionTitle: '這個決定有什麼風險？',
    objectionBody: '你可以修改決定，也可以承認這個代價後仍維持原案。兩種選擇都不會被判錯。',
    revise: '修改我的決定', hold: '我了解風險，維持決定', fixedProcess: '固定情境 · 不評分立場',
    lampLabel: '已看過 {count} 個角度', lampNote: '燈亮代表看過，不代表答對。',
    hintToast: '這裡沒有隱藏答案。請選你最想繼續追查的方向。', angleAnnounce: '已看過這個角度；這不是標準答案排名。',
  },
  completion: {
    sessionCode: '本輪完成', dailyCode: '每日案件',
    sceneTitle: '你已經從六個角度看過這件事。',
    sceneBody: '你得到的不是系統認證的「正確立場」，而是一個說得出理由、看得到風險，也知道什麼證據會改變它的決定。',
    expeditionTitle: '預測完成；真正重要的是校準。',
    expeditionBody: '你分開判斷了突破幅度、模型信心與適用範圍，沒有把 CASP14 的結果擴大成所有問題都已解決。',
    detectiveTitle: '第二步真的用上了第一步的線索。',
    detectiveBody: '你比較的是同一批團隊，而不是把全公司和六個自願參與的資深團隊混在一起。這只是兩步固定示範；完整辦案流程在 CLI／Skill。',
    drillTitle: '今天的推理快問完成了。',
    drillBody: '每題都留下了一個可重複使用的推理方法；答錯的地方也已經攤開說明。',
    sceneDetails: [['看過的角度', '6 / 6'], ['檢查反面證據', '完成'], ['做出決定', '完成']],
    expeditionDetails: [['校準命中', '{hits} / {total}'], ['完成預測', '{total}'], ['資料來源', 'CASP14']],
    hits: '答對題數', clues: '練過的推論', mode: '練習模式', replay: '再玩一次', choose: '選另一個模式',
    dailySceneTitle: '六個角度都看過了；這裡沒有偷藏標準立場。', dailyTitle: '今日案件已完成。',
    dailySceneBody: '你完成的是一輪觀察，不是價值立場測驗。明天會換一宗案件；四種固定示範仍可不限次練習。',
    dailyBody: '伺服器只回傳這次需要的解析。這七題也出現在公開離線示範中，因此只適合展示流程，不是防作弊題庫。每日案件依台北日期更新。',
    reviewedAngles: '看過的角度', dailyCase: '今日模式', reread: '重新閱讀', lobby: '回案件大廳',
  },
  passport: {
    code: '本機練習紀錄', title: '調查員護照', modeCount: '四種模式完成次數', localTitle: '只記在這台裝置',
    localBody: '保存 XP、完成日期、模式與推理類型；情境模式的自由文字不會寫入 localStorage。清除瀏覽器資料會一併刪除。',
    delete: '刪除本機護照',
  },
  routes: {
    code: '同一套核心 · 三種入口', title: '三種使用方式，不互相取代',
    cliTitle: 'CLI 完整版', cliBody: '四種動態模式、AI 對話、遠征資料包與本機護照。適合下載程式碼庫後，透過支援的 AI 助理或 CLI 使用。',
    zipTitle: 'Skill ZIP／聊天版', zipBody: '把打包檔上傳到支援的平台。Claude.ai ZIP 含四種模式；portable Markdown 是相容版本，目前不含 Expedition。',
    webTitle: '網頁遊戲示範版', webBody: '給不熟 CLI 的人使用。四種固定雙語路線可直接玩；每日案件 API 啟用後，首頁會再顯示每天輪換的案件。',
    warningTitle: '聊天訂閱不等於第三方 API 額度',
    warningBody: 'ChatGPT Plus、Claude Pro、Google AI Pro 或 SuperGrok 通常不能直接替獨立網站支付模型推論費。本站不會要求你的密碼、Cookie 或 session token；正式串接必須使用平台允許的 OAuth／API，或由產品端負擔額度。',
    confirm: '了解，繼續玩',
  },
}

const en = {
  meta: {
    title: 'The Doubt Bureau Casebook | Daily reasoning practice',
    description: 'Practice critical thinking through a bilingual retro detective game: quick drills, scene analysis, scientific forecasting, and case auditing.',
    noscript: 'This interactive demo requires JavaScript.',
  },
  language: { label: 'Language', zh: '中文', en: 'EN', changed: 'Language changed to English' },
  common: {
    close: 'Close', back: 'Back to mode selection', exitMode: 'Leave this mode', exitDaily: 'Leave today’s case',
    progress: 'Progress', fixedDemo: 'Fixed demo', fixedCase: 'Fixed case', continue: 'Continue', replay: 'Play again',
    xpEarned: 'XP earned', on: 'On', off: 'Off', retry: 'Retry',
  },
  brand: { seal: '?', name: 'Doubt Bureau', subtitle: 'CASEBOOK' },
  audio: {
    code: 'Sound desk',
    musicOn: 'Turn background music off', musicOff: 'Turn background music on', sfxOn: 'Turn answer sounds off', sfxOff: 'Turn answer sounds on',
    settings: 'Audio settings', title: 'Audio settings', music: 'Background music', musicDescription: 'Original retro mystery score; playback begins after your first interaction.',
    volume: 'Music volume', sfx: 'Answer sounds', sfxDescription: 'Paper, clue, success, and correction cues.',
    browserNote: 'Your browser’s autoplay rules apply. Music pauses while this tab is in the background.',
  },
  stats: {
    label: 'Player progress', streak: 'Practice streak', day: 'days', clues: 'Clues found', rank: 'Investigator rank',
    passport: 'Passport', passportLabel: 'Open investigator passport', sessions: 'Sessions', level: 'Level {level}', toNext: '{xp} XP to next level',
  },
  home: {
    practice: 'Today’s practice', overline: 'Choose your method', titleBefore: 'Which door will you open', titleEmphasis: 'to start tonight’s inquiry?',
    intro: 'Choose a domain first, then open a matching Daily case or bilingual fixed demo. Every mode states its subject, mechanic, and limits before you begin.',
    circuitLabel: 'Today’s four-mode progress', circuit: 'Daily circuit',
    circuitDone: 'You have visited all four modes today. Every route remains replayable.',
    circuitOpen: 'Completing any mode extends your streak. All four routes are freely replayable.',
    sectionCode: 'Four modes · four thinking stances', sectionTitle: 'Choose tonight’s case',
    sectionNote: 'These are fixed, replayable bilingual demos—not the full dynamic CLI/Skill sessions.',
    completed: 'Completed today · replay', routeLabel: 'Three ways to use the project', routeButton: 'Compare access and sign-in limits',
    routesSummary: 'CLI, Skill ZIP, and the web game are parallel entry points with different capabilities and account limits.',
    routes: {
      cli: 'All four dynamic modes, AI dialogue, and a local Passport.',
      zip: 'Upload to a supported platform for conversational play.',
      web: 'A no-CLI entry point with fixed demos and an optional Daily case.',
    },
    privacyFooter: '4 BILINGUAL FIXED DEMOS + OPTIONAL DAILY API · FREE TEXT IS NOT UPLOADED',
  },
  domains: {
    code: 'Step 1 of 2 · choose a case domain', title: 'What kind of problem do you want to investigate?',
    intro: 'Your matching cases and modes appear only after this choice. Choose Mixed casebook to see all four modes.',
    chooseFirst: 'Choose a domain; its cases will open immediately below.', complete: 'Step 1 complete',
    selected: 'Selected: {domain}', stepTwo: 'Step 2 of 2 · choose a practice mode', change: 'Change domain', available: '{count} playable demos',
    labels: { all: 'Mixed casebook', education: 'Education', health: 'Health & medicine', public: 'Public affairs', science: 'Science & technology', work: 'Work & business' },
    descriptions: {
      all: 'Mixed subjects with all four modes available.', education: 'Audit evidence about courses and learning outcomes.', health: 'Reason about risk, screening, and base rates.',
      public: 'News judgment, road safety, and public decisions.', science: 'Forecast the size and limits of a scientific advance.', work: 'Audit AI performance claims and business metrics.',
    },
    drillExcerpt: '{count} fixed beginner question(s) are currently available for {domain}. Every option is explained after you answer.', drillMechanic: '{count}-question domain excerpt',
    drillBoundary: 'A fixed {count}-question beginner demo with a per-option explanation. Use the CLI/Skill for dynamic generation and answer challenges.',
    noCases: 'No fixed case is available in this domain yet.',
  },
  daily: {
    labels: { drill: 'Quick drill', scene: 'Scene study', expedition: 'Forecast', detective: 'Case audit' },
    loading: 'A telegram is crossing the fog. Today’s case will arrive shortly.',
    readyScene: 'Examine one scene from six angles. Your position is not scored.',
    readyChoice: '{count} evidence files; the server returns the explanation for this attempt after you commit.',
    complete: 'Today’s case is closed. You may replay it without earning the reward twice.',
    unavailableCase: 'The public preview arrived, but server explanations are not deployed. The four fixed demos still work.',
    unavailable: 'Daily service is not enabled. The four fixed demos still work.',
    localeUnavailable: 'Today’s Daily case is currently available only in Traditional Chinese. Switch to 中文 or try any English demo below.',
    reopen: 'Replay today’s case', open: 'Open today’s case', receiving: 'Receiving case', disabled: 'Explanation unavailable', retryLabel: 'Request today’s case again',
    connecting: 'CONNECTING', timezone: 'Updated daily · Asia/Taipei', preview: 'PUBLIC PREVIEW / SERVER OFFLINE', closed: 'CASE CLOSED · REPLAY',
    duration: 'ONE CASE A DAY · 3–7 MIN', arriving: 'Today’s case is arriving', mode: 'Mode', waiting: 'Waiting', ruling: 'Review',
    sealed: 'Server response', neutral: 'Unscored process', notEnabled: 'Unavailable', dispatch: 'Daily dispatch',
    publicPrivate: 'Daily case · public prompt / server explanation', answerOnly: 'Only the option ID is sent', checking: 'Checking your answer…',
    sceneExcerpt: 'Daily scene excerpt · positions are not scored', sceneRead: 'Read the scene before judging it', sceneNoText: 'The Daily excerpt does not upload free text', firstAngle: 'View the first angle',
    caseExpired: 'The date has changed in Taipei. Return to the lobby to receive the new case.',
    rulingError: 'The review room did not respond. Your selection is still here; you can retry.',
    hitAnnounce: 'Correct. You earned {xp} XP.', missAnnounce: 'Explanation unlocked. You earned {xp} XP.', expiredAnnounce: 'Today’s case has changed', errorAnnounce: 'The review room is temporarily unavailable',
  },
  brief: {
    route: 'This excerpt', duration: 'Estimated time', source: 'Source constraints', chooseAnother: 'Choose another mode', enter: 'Start {mode}',
    caseFrameTitle: 'What is this case testing?', frameClaim: 'Claim', frameSuccess: 'What success requires', frameStandard: 'Decision standard', frameEvidence: 'Allowed evidence',
    boundaries: {
      drill: 'A fixed three-question beginner demo. Each item has one defensible answer and a per-option explanation. Use the CLI/Skill for dynamic generation and answer challenges.',
      scene: 'Your position is not scored. A lit marker means you examined one angle; it does not mean the system endorses your values.',
      expedition: 'A fixed Forecaster excerpt grounded in AlphaFold 2 at CASP14. The goal is calibration—not solving protein structure, and not a complete Expedition.',
      detective: 'A two-step beginner audit. Step one yields a value that step two requires. Free-form objections, optional additional defects, and full case generation remain CLI/Skill features.',
    },
  },
  play: {
    sealed: 'The file is still sealed', inspect: 'Open the file', hint: 'Give me a hint', lockPrediction: 'Lock forecast', lockAnswer: 'Lock answer',
    fixedVersion: 'Fixed demo · Skill {version}', hit: 'Correct', review: 'Recheck', answerIs: 'Answer: {answer}', keyFound: 'Key inference found',
    explainAgain: 'Explain again', summary: 'Review this run', next: 'Next question',
    practiceNote: 'Wrong answers cost no lives. The explanation turns the miss into a reusable clue.',
    forecastNote: 'This records forecast calibration; it does not imply you solved the science.',
    challengeNote: 'Disagree with the ruling? The CLI/Skill version accepts challenges; this fixed web demo can only show its prepared analysis.',
    earned: '{result}. You earned {xp} XP.', unlocked: 'Explanation unlocked',
    whyOptions: 'Option-by-option review', chosen: 'Your choice', correct: 'Key', distractor: 'Other option',
  },
  scene: {
    observeCode: 'Observe before interpreting', observeTitle: 'Write down only what you can observe',
    observeBody: 'Do not decide what it means yet. No analysis angles are shown at this stage. Record only what the text actually gives you.',
    observationLabel: 'My first observations', observationPlaceholder: 'Put the observable facts in your own words…',
    localOnly: 'This text stays in the current tab and is never written to your Passport.', saveObservation: 'Save observation',
    angleCode: 'Angle', reviewed: 'Angle reviewed', noPreferred: 'There is no hidden preferred position', nextSelf: 'Examine your own view', nextAngle: 'Next angle',
    angleHint: 'What does this angle examine?', reviewAngle: 'Review this angle',
    cameraCode: 'Examine your own view', cameraTitle: 'Where do you currently stand?',
    cameraBody: 'This is not a test. Choose a provisional position, then name something it may be missing.', blindspotLabel: 'This view may be missing…',
    blindspotPlaceholder: 'Name one possible blind spot…', revisable: 'A provisional view can change when the evidence changes.', savePosition: 'Save provisional view',
    commitmentCode: 'Make the call', commitmentTitle: 'What would you do tonight?',
    commitmentBody: 'Choose a course of action you can currently defend, then give your reason. The system will present a serious objection.',
    reasonLabel: 'My reason', reasonPlaceholder: 'I would choose this because…', noPreference: 'The options do not signal a preferred answer', pressure: 'Show the objection',
    objectionCode: 'A serious objection', objectionTitle: 'What is the risk in this decision?',
    objectionBody: 'You may revise your decision, or acknowledge the cost and still hold it. Neither response is graded as wrong.',
    revise: 'Revise my decision', hold: 'I accept the risk and hold my decision', fixedProcess: 'Fixed scene · positions are not scored',
    lampLabel: '{count} angles reviewed', lampNote: 'Lit means reviewed, not correct.',
    hintToast: 'There is no hidden answer here. Choose the line of inquiry you most want to pursue.', angleAnnounce: 'Angle reviewed. This is not a ranking of correct positions.',
  },
  completion: {
    sessionCode: 'Session complete', dailyCode: 'Daily dispatch',
    sceneTitle: 'You examined the scene from six angles.',
    sceneBody: 'You did not receive a system-approved “correct position.” You made a reasoned decision, saw its risks, and named what could change it.',
    expeditionTitle: 'Forecast complete. Calibration is the real result.',
    expeditionBody: 'You separated the size of the advance, confidence calibration, and scope—without turning a CASP14 result into a claim that every problem was solved.',
    detectiveTitle: 'Step two genuinely used the clue from step one.',
    detectiveBody: 'You compared the same teams instead of mixing a company-wide baseline with a selected group of senior volunteers. This is a fixed two-step demo; the full case mode lives in the CLI/Skill.',
    drillTitle: 'Tonight’s quick drills are complete.',
    drillBody: 'Each answer leaves behind a reusable reasoning pattern, and every miss has been explained rather than hidden.',
    sceneDetails: [['Angles reviewed', '6 / 6'], ['Counter-evidence', 'Complete'], ['Decision made', 'Complete']],
    expeditionDetails: [['Calibrated calls', '{hits} / {total}'], ['Forecasts made', '{total}'], ['Source pack', 'CASP14']],
    hits: 'Correct answers', clues: 'Patterns practised', mode: 'Practice mode', replay: 'Play again', choose: 'Choose another mode',
    dailySceneTitle: 'Six angles reviewed, with no hidden preferred position.', dailyTitle: 'Today’s case is closed.',
    dailySceneBody: 'You completed an observation route, not a values test. A new case arrives tomorrow; the four fixed demos remain replayable.',
    dailyBody: 'The server returned only the explanation needed for this attempt. These seven fixtures also appear in the public offline demo, so they demonstrate the flow rather than anti-cheat integrity. Daily cases follow the Taipei date.',
    reviewedAngles: 'Angles reviewed', dailyCase: 'Today’s mode', reread: 'Read again', lobby: 'Back to case lobby',
  },
  passport: {
    code: 'Local practice record', title: 'Investigator Passport', modeCount: 'Completions by mode', localTitle: 'Stored only on this device',
    localBody: 'Stores XP, completion dates, modes, and reasoning patterns. Free text from Scene is never written to localStorage. Clearing browser data removes this record.',
    delete: 'Delete local Passport',
  },
  routes: {
    code: 'One core · three entries', title: 'Three ways to play; none replaces the others',
    cliTitle: 'Full CLI edition', cliBody: 'Four dynamic modes, AI dialogue, Expedition packs, and a local Passport. Clone the repository and use it in a supported agent or CLI.',
    zipTitle: 'Skill ZIP / chat edition', zipBody: 'Upload a packaged skill to a supported platform. The Claude.ai ZIP includes four modes; portable Markdown is a compatibility build and currently omits Expedition.',
    webTitle: 'Web game demo', webBody: 'The no-CLI entry point. Four fixed bilingual routes work in the browser; an optional Daily API can add one rotating case with server-returned explanations.',
    warningTitle: 'A chat subscription is not third-party API credit',
    warningBody: 'ChatGPT Plus, Claude Pro, Google AI Pro, and SuperGrok generally cannot pay for inference on an independent website. This site never asks for your password, cookies, or session token. A production integration must use an approved OAuth/API flow or product-funded usage.',
    confirm: 'Got it—keep playing',
  },
}

export const uiCopy = Object.freeze({ 'zh-TW': Object.freeze(zhTW), en: Object.freeze(en) })

export const getUiCopy = (locale) => uiCopy[resolveLocale(locale)]

export const interpolate = (template, values = {}) => String(template).replace(/\{(\w+)\}/g, (_, key) => values[key] ?? `{${key}}`)
